# URLs app file for r2h2_app app
from django.urls import path
from . import views

urlpatterns = [
    path('', views.landing, name='dashboard-landing'),
    path('components', views.home, name='dashboard-home'),
    path('simulations/', views.simulations, name='dashboard-simulations'),
    path('simulations/create/', views.create_simulation, name='dashboard-create-simulation'),
    path('simulations/create-default/', views.create_default_model, name='dashboard-create-default-model'),
    path('simulations/<int:sim_id>/update/', views.update_simulation, name='dashboard-update-simulation'),
    path('simulations/<int:sim_id>/delete/', views.delete_simulation, name='dashboard-delete-simulation'),
    path('simulations/<int:sim_id>/', views.simulation_detail, name='dashboard-simulation-detail'),
    path('simulations/<int:sim_id>/link/', views.link_components, name='dashboard-link-components'),
    path('simulations/<int:sim_id>/unlink/', views.unlink_component, name='dashboard-unlink-component'),
    path('simulations/<int:sim_id>/wind-reorder/', views.reorder_wind_inputs, name='dashboard-wind-reorder'),
    path('simulations/<int:sim_id>/wind-year/', views.update_wind_year, name='dashboard-wind-year'),
    path('simulations/<int:sim_id>/wind-first-year/', views.update_first_wind_year, name='dashboard-wind-first-year'),
    path('simulations/<int:sim_id>/duration/', views.update_sim_duration, name='dashboard-update-sim-duration'),
    path('simulations/<int:sim_id>/date-range/', views.update_sim_date_range, name='dashboard-update-sim-date-range'),
    path('simulations/<int:sim_id>/datum/',    views.update_sim_datum,    name='dashboard-update-sim-datum'),
    path('simulations/<int:sim_id>/1hz/',      views.update_sim_1hz,      name='dashboard-update-sim-1hz'),
    path('simulations/<int:sim_id>/controller/', views.update_sim_controller, name='dashboard-update-sim-controller'),
    path('controllers/save/', views.save_controller_file, name='dashboard-save-controller'),
    path('controllers/get/',  views.get_controller_file,  name='dashboard-get-controller'),
    path('controllers/rename/', views.rename_controller_file, name='dashboard-rename-controller'),
    path('simulations/<int:sim_id>/wind-preview/', views.wind_preview_data, name='dashboard-wind-preview'),
    path('simulations/<int:sim_id>/run/',                views.run_simulation,    name='dashboard-run-simulation'),
    path('simulations/<int:sim_id>/run/<int:run_id>/',          views.poll_simulation_run,   name='dashboard-poll-simulation-run'),
    path('simulations/<int:sim_id>/run/<int:run_id>/cancel/',   views.cancel_simulation_run,  name='dashboard-cancel-simulation-run'),
    path('simulations/<int:sim_id>/run/<int:run_id>/delete/',   views.delete_simulation_run,  name='dashboard-delete-simulation-run'),
    path('simulations/<int:sim_id>/run/<int:run_id>/description/', views.update_run_description, name='dashboard-update-run-description'),
    path('simulations/<int:sim_id>/run/<int:run_id>/download/',     views.download_run_output,      name='dashboard-download-run-output'),
    path('simulations/<int:sim_id>/run/<int:run_id>/results/',     views.view_run_results,         name='dashboard-run-results'),
    path('simulations/<int:sim_id>/run/<int:run_id>/xaxis/',      views.update_run_xaxis,          name='dashboard-update-run-xaxis'),
    path('browse/<str:table_name>', views.browse, name='dashboard-browse'),
    path('browse/<str:table_name>/add', views.add_component, name='dashboard-add-component'),
    path('browse/<str:table_name>/<int:pk>/get', views.get_component, name='dashboard-get-component'),
    path('browse/<str:table_name>/<int:pk>/edit', views.edit_component, name='dashboard-edit-component'),
    path('browse/<str:table_name>/<int:pk>/delete', views.delete_component, name='dashboard-delete-component'),
    path('wind-data/', views.wind_data, name='dashboard-wind-data'),
    path('wind-data/upload/', views.wind_data_upload, name='dashboard-wind-data-upload'),
    path('wind-data/set-dir/', views.wind_data_set_dir, name='dashboard-wind-data-set-dir'),
    path('help/', views.help_page, name='dashboard-help'),
    path('help/git-pull/', views.git_pull, name='dashboard-git-pull'),
    path('help/restart/', views.restart_app, name='dashboard-restart-app'),
    path('settings/', views.app_settings, name='dashboard-settings'),
    path('settings/save/', views.settings_save, name='dashboard-settings-save'),
]
