# Generated by Django 6.0.2 on 2026-02-26 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Battery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rKt_lc', models.FloatField(default=4.14e-10)),
                ('rKs', models.FloatField(default=1.04)),
                ('rKT_uc', models.FloatField(default=0.0693)),
                ('rAlphaSei', models.FloatField(default=0.0575)),
                ('rKd1', models.FloatField(default=140000.0)),
                ('rKd2', models.FloatField(default=-0.501)),
                ('rKd3', models.FloatField(default=-123000.0)),
                ('rBetaSei', models.FloatField(default=121.0)),
                ('rTcRef', models.FloatField(default=55.0)),
                ('rSoCRef', models.FloatField(default=0.5)),
                ('arInitialSoC', models.FloatField(default=0.5)),
                ('rFt', models.FloatField(default=0.0)),
                ('rFc', models.FloatField(default=0.0)),
                ('rBatteryMWh', models.FloatField(default=15)),
                ('rInitialBatteryRating', models.FloatField(default=0.0)),
                ('rBatteryRating', models.FloatField(default=0.0)),
                ('rRCD', models.FloatField(default=1.0)),
                ('rControlMinSoC', models.FloatField(default=0.5)),
                ('rBatteryProportionalGain', models.FloatField(default=0.0)),
                ('iNumReplacements', models.FloatField(default=0)),
                ('aiReplacementHour', models.FloatField(default=0)),
                ('rSocAv', models.FloatField(default=0.0)),
                ('rSocMax', models.FloatField(default=0.0)),
                ('rSocMin', models.FloatField(default=0.0)),
                ('rDodAv', models.FloatField(default=0.0)),
                ('arBatteryPower', models.FloatField(default=None)),
                ('arSoC', models.FloatField(default=None)),
                ('arDoD', models.FloatField(default=None)),
                ('arBatteryDemand', models.FloatField(default=None)),
            ],
        ),
    ]
