# Generated by Django 6.0.2 on 2026-02-26 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='battery',
            name='name',
            field=models.CharField(default='Battery', max_length=100),
        ),
        migrations.AlterField(
            model_name='battery',
            name='aiReplacementHour',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='battery',
            name='arBatteryDemand',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='battery',
            name='arBatteryPower',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='battery',
            name='arDoD',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='battery',
            name='arSoC',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='battery',
            name='iNumReplacements',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
