# Generated by Django 6.0.2 on 2026-02-26 11:11

import dashboard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_battery_name_alter_battery_aireplacementhour_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectroCellPEM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='ElectroCellPEM', max_length=100)),
                ('rR', models.FloatField(default=8.314)),
                ('rF', models.FloatField(default=96485.0)),
                ('arCurrentDensity', models.JSONField(default=list)),
                ('arE_min', models.JSONField(default=list)),
                ('arR_cell', models.JSONField(default=list)),
                ('arV_cell', models.JSONField(default=list)),
                ('iNumCurrent', models.FloatField(default=1000)),
                ('rA_cell', models.FloatField(default=1000.0, help_text='cm^2')),
                ('rI_rated', models.FloatField(default=3.0, help_text='A/cm^2')),
                ('rT_0', models.FloatField(default=55.0, help_text='Nominal operating temperature [°C]')),
                ('rT', models.FloatField(default=55.0, help_text='Initial operating temperature [°C]')),
                ('rE_min0', models.FloatField(default=1.55)),
                ('rR_0', models.FloatField(default=0.178, help_text='should be x2 according to literature but polarization curve would be too steep')),
                ('rD_rt', models.FloatField(default=-0.0045, help_text='dR/dT')),
                ('rV_cellNom', models.FloatField(default=2.1)),
                ('rV_bank', models.FloatField(default=633.5)),
                ('rI_bank', models.FloatField(default=3000.0)),
                ('rF1', models.FloatField(default=0.25)),
                ('rF2', models.FloatField(default=0.996)),
                ('arFaradayTemp_C', models.JSONField(default=dashboard.models.default_faraday_temp)),
                ('arFaradayF1', models.JSONField(default=dashboard.models.default_faraday_f1)),
                ('arFaradayF2', models.JSONField(default=dashboard.models.default_faraday_f2)),
            ],
        ),
    ]
