# Generated by Django 6.0.3 on 2026-03-08 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_electrocellpem'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectrolyserUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='ElectrolyserUnit', max_length=100)),
                ('iN_stacks', models.PositiveIntegerField(default=0)),
                ('iN_banks', models.PositiveIntegerField(default=0)),
                ('iNumElectro', models.PositiveIntegerField(default=0)),
                ('iN_cell', models.PositiveIntegerField(default=0)),
                ('iControlLevel', models.PositiveIntegerField(choices=[(1, 'Electrolyser'), (2, 'Bank'), (3, 'Stack')], default=2)),
                ('rTimeConst', models.FloatField(default=30.0)),
                ('rDegradation', models.FloatField(default=1e-30)),
                ('rTurnDownRatio', models.FloatField(default=0.125)),
                ('r_s', models.FloatField(default=1.42e-10)),
                ('r_f', models.FloatField(default=3.33e-07)),
                ('r_o', models.FloatField(default=0.000147)),
                ('rAncilliaryPowerFrac', models.FloatField(default=0.0, help_text='Always required (For WT and all - set to zero for weak grid rather than off gid)')),
                ('rDeadBandRatio', models.FloatField(default=2.0)),
                ('rRampUp_W_s', models.FloatField(default=None)),
                ('rRampDown_W_s', models.FloatField(default=None)),
                ('iNumUnits', models.PositiveIntegerField(default=0)),
                ('rTotalTurnOns', models.FloatField(default=0.0)),
                ('rSummedDegradation', models.FloatField(default=1e-30)),
                ('arDegradationTotal', models.JSONField(default=None)),
                ('arV_s', models.JSONField(default=None)),
                ('arV_sd', models.JSONField(default=None)),
                ('arI_s', models.JSONField(default=None)),
                ('arH2Dot_s', models.JSONField(default=None)),
                ('arP_Total_s', models.JSONField(default=None)),
                ('arEfficiency_s', models.JSONField(default=None)),
                ('rRatedPower_s', models.FloatField(default=0.0)),
                ('rMinPower_s', models.FloatField(default=0.0)),
                ('rAncilliaryPower_s', models.FloatField(default=0.0)),
                ('arDegradationSteady', models.JSONField(default=None)),
                ('arDegradationFatigue', models.JSONField(default=None)),
                ('arDegradationOnOff', models.JSONField(default=None)),
                ('rDegradationOnOffTotal', models.FloatField(default=0.0)),
                ('rDegradationSteadyTotal', models.FloatField(default=0.0)),
                ('rDegradationFatigueTotal', models.FloatField(default=0.0)),
            ],
        ),
    ]
