# Generated by Django 6.0.3 on 2026-03-08 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_electrolyserunit'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThermalProperties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='ThermalProperties', max_length=100)),
                ('rAmbientTemp', models.FloatField(default=15.0)),
                ('rTauHeating', models.FloatField(default=120.0, help_text='Time constant for heating (seconds)')),
                ('rTauCooling', models.FloatField(default=180.0, help_text='Time constant for cooling (seconds)')),
                ('rTargetTemp', models.FloatField(default=60.0, help_text='Target operating temperature (°C)')),
                ('rMinTemp', models.FloatField(default=50.0, help_text='Minimum operating temperature (°C)')),
            ],
        ),
    ]
