# Generated by Django 6.0.3 on 2026-03-08 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_thermalproperties'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeOutput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='TimeOutput', max_length=100)),
                ('arTime', models.JSONField(default=list)),
                ('arWindPowerFilt', models.JSONField(default=list)),
                ('arAvailablePower', models.JSONField(default=list)),
                ('arElectroAvailablePowerA', models.JSONField(default=list)),
                ('arElectroAvailablePower', models.JSONField(default=list)),
                ('rPreviousValue', models.FloatField(default=0.0)),
                ('arTotalElectroDemand', models.JSONField(default=list)),
                ('arProportionPower', models.JSONField(default=list)),
                ('aiIsOn', models.JSONField(default=list)),
                ('aiWarmedUp', models.JSONField(default=list)),
                ('aiNumOn', models.JSONField(default=list)),
                ('arTotalElectroOn', models.JSONField(default=list)),
                ('arElectroDemand', models.JSONField(default=list)),
                ('arI_unit', models.JSONField(default=list)),
                ('arV_unit', models.JSONField(default=list)),
                ('arV_unitUseful', models.JSONField(default=list)),
                ('arPower_unit', models.JSONField(default=list)),
                ('arPower_unitUseful', models.JSONField(default=list)),
                ('arDegradationInEfficiency', models.JSONField(default=list)),
                ('arV_cell', models.JSONField(default=list)),
                ('arProducedH2Dot', models.JSONField(default=list)),
                ('arHydroEfficiency', models.JSONField(default=list)),
                ('arP_el_total', models.JSONField(default=list)),
                ('arT_stack', models.JSONField(default=list)),
                ('arH2Dot_total', models.JSONField(default=list)),
                ('arV_cell_avg', models.JSONField(default=list)),
                ('arEta_el_total', models.JSONField(default=list)),
                ('arEta_system_total', models.JSONField(default=list)),
                ('arP_el_banks', models.JSONField(default=list)),
                ('arT_banks', models.JSONField(default=list)),
                ('arP_el_unit', models.JSONField(default=list)),
                ('arQ_gain_unit', models.JSONField(default=list)),
                ('arVtn_unit', models.JSONField(default=list)),
                ('arT_unit_bank', models.JSONField(default=list)),
                ('arQ_gain_banks', models.JSONField(default=list)),
                ('arQ_lost_banks', models.JSONField(default=list)),
                ('arQ_cool_banks', models.JSONField(default=list)),
                ('arP_cool_elec_banks', models.JSONField(default=list)),
                ('arG_eq_banks', models.JSONField(default=list)),
                ('arC_th_banks', models.JSONField(default=list)),
                ('arQ_gain_total', models.JSONField(default=list)),
                ('arQ_lost_total', models.JSONField(default=list)),
                ('arQ_cool_total', models.JSONField(default=list)),
                ('arP_cool_elec_total', models.JSONField(default=list)),
            ],
        ),
        migrations.AlterField(
            model_name='electrolyserunit',
            name='arDegradationFatigue',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='electrolyserunit',
            name='arDegradationOnOff',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='electrolyserunit',
            name='arDegradationSteady',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='electrolyserunit',
            name='arDegradationTotal',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='electrolyserunit',
            name='arEfficiency_s',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='electrolyserunit',
            name='arH2Dot_s',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='electrolyserunit',
            name='arI_s',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='electrolyserunit',
            name='arP_Total_s',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='electrolyserunit',
            name='arV_s',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='electrolyserunit',
            name='arV_sd',
            field=models.JSONField(default=list),
        ),
    ]
