# Generated by Django 6.0.3 on 2026-03-08 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_timeoutput_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WindInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='WindInput', max_length=100)),
                ('arPowerInput', models.JSONField(default=list)),
                ('arTime', models.JSONField(default=list)),
            ],
        ),
    ]
