# Generated by Django 6.0.3 on 2026-03-09 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_windinput'),
    ]

    operations = [
        migrations.CreateModel(
            name='Simulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Simulation', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(default='User', max_length=100)),
                ('batteries', models.ManyToManyField(blank=True, to='dashboard.battery')),
                ('electro_cells', models.ManyToManyField(blank=True, to='dashboard.electrocellpem')),
                ('electrolyser_units', models.ManyToManyField(blank=True, to='dashboard.electrolyserunit')),
                ('thermal_properties', models.ManyToManyField(blank=True, to='dashboard.thermalproperties')),
                ('time_outputs', models.ManyToManyField(blank=True, to='dashboard.timeoutput')),
                ('wind_inputs', models.ManyToManyField(blank=True, to='dashboard.windinput')),
            ],
        ),
    ]
