# Generated by Django 6.0.3 on 2026-03-09 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_simulation'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulation',
            name='arLateralDistances',
            field=models.JSONField(default=list, help_text='Lateral distances of turbines in weak grid scenario (meters)'),
        ),
        migrations.AddField(
            model_name='simulation',
            name='bSingleTurb',
            field=models.BooleanField(default=True, help_text='Whether to simulate a single turbine or multiple (weak grid)'),
        ),
        migrations.AddField(
            model_name='simulation',
            name='iNumYears',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='simulation',
            name='iWindType',
            field=models.PositiveIntegerField(choices=[(0, '1 sec'), (1, '1 min'), (2, '10 min'), (3, 'hourly')], default=0),
        ),
        migrations.AddField(
            model_name='simulation',
            name='rDivisor',
            field=models.FloatField(default=400.0, help_text='Divisor for normalizing wind power input (e.g. max power of single turbine)'),
        ),
        migrations.AddField(
            model_name='simulation',
            name='rTimeStep',
            field=models.FloatField(default=1.0, help_text='Time step in seconds'),
        ),
        migrations.AddField(
            model_name='simulation',
            name='rTotalTime',
            field=models.FloatField(default=3700.0, help_text='Total simulation time in seconds'),
        ),
        migrations.AddField(
            model_name='simulation',
            name='rTransientSteps',
            field=models.PositiveIntegerField(default=101, help_text='Number of initial transient steps to discard in analysis'),
        ),
    ]
