# Generated by Django 6.0.3 on 2026-03-09 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_alter_battery_aireplacementhour_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battery',
            name='aiReplacementHour',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='battery',
            name='arBatteryDemand',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='battery',
            name='arBatteryPower',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='battery',
            name='arDoD',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='battery',
            name='arSoC',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='electrocellpem',
            name='arCurrentDensity',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='electrocellpem',
            name='arE_min',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='electrocellpem',
            name='arR_cell',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='electrocellpem',
            name='arV_cell',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='electrolyserunit',
            name='arDegradationFatigue',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='electrolyserunit',
            name='arDegradationOnOff',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='electrolyserunit',
            name='arDegradationSteady',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='electrolyserunit',
            name='arDegradationTotal',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='electrolyserunit',
            name='arEfficiency_s',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='electrolyserunit',
            name='arH2Dot_s',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='electrolyserunit',
            name='arI_s',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='electrolyserunit',
            name='arP_Total_s',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='electrolyserunit',
            name='arV_s',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='electrolyserunit',
            name='arV_sd',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='arLateralDistances',
            field=models.JSONField(blank=True, default=None, help_text='Lateral distances of turbines in weak grid scenario (meters)', null=True),
        ),
        migrations.AlterField(
            model_name='timeoutput',
            name='aiIsOn',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='timeoutput',
            name='aiNumOn',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='timeoutput',
            name='aiWarmedUp',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='timeoutput',
            name='arAvailablePower',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='timeoutput',
            name='arC_th_banks',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='timeoutput',
            name='arDegradationInEfficiency',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='timeoutput',
            name='arElectroAvailablePower',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='timeoutput',
            name='arElectroAvailablePowerA',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='timeoutput',
            name='arElectroDemand',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='timeoutput',
            name='arEta_el_total',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='timeoutput',
            name='arEta_system_total',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='timeoutput',
            name='arH2Dot_total',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='timeoutput',
            name='arHydroEfficiency',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='timeoutput',
            name='arI_unit',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='timeoutput',
            name='arP_cool_elec_banks',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='timeoutput',
            name='arP_cool_elec_total',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='timeoutput',
            name='arP_el_banks',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='timeoutput',
            name='arP_el_total',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='timeoutput',
            name='arP_el_unit',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='timeoutput',
            name='arPower_unit',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='timeoutput',
            name='arPower_unitUseful',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='timeoutput',
            name='arProducedH2Dot',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='timeoutput',
            name='arProportionPower',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='timeoutput',
            name='arQ_cool_banks',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='timeoutput',
            name='arQ_cool_total',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='timeoutput',
            name='arQ_gain_banks',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='timeoutput',
            name='arQ_gain_total',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='timeoutput',
            name='arQ_gain_unit',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='timeoutput',
            name='arQ_lost_banks',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='timeoutput',
            name='arQ_lost_total',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='timeoutput',
            name='arT_banks',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='timeoutput',
            name='arT_stack',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='timeoutput',
            name='arT_unit_bank',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='timeoutput',
            name='arTime',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='timeoutput',
            name='arTotalElectroDemand',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='timeoutput',
            name='arTotalElectroOn',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='timeoutput',
            name='arV_cell',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='timeoutput',
            name='arV_cell_avg',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='timeoutput',
            name='arV_unit',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='timeoutput',
            name='arV_unitUseful',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='timeoutput',
            name='arVtn_unit',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='timeoutput',
            name='arWindPowerFilt',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='windinput',
            name='arPowerInput',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='windinput',
            name='arTime',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
