# Generated by Django 6.0.3 on 2026-03-26 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_simulationrun'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electrocellpem',
            name='iNumCurrent',
            field=models.PositiveIntegerField(default=1000),
        ),
    ]
