# Generated by Django 6.0.3 on 2026-04-23 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_alter_electrocellpem_inumcurrent'),
    ]

    operations = [
        migrations.AddField(
            model_name='windinput',
            name='wind_file',
            field=models.FileField(blank=True, help_text='HDF5 wind data file (.h5 / .hdf5 / .hdf)', null=True, upload_to='wind_data/'),
        ),
    ]
