# Generated by Django 6.0.3 on 2026-05-05 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_windinput_wind_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electrolyserunit',
            name='rRampDown_W_s',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='electrolyserunit',
            name='rRampUp_W_s',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='simulationrun',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('done', 'Done'), ('error', 'Error'), ('cancelled', 'Cancelled')], default='pending', max_length=16),
        ),
    ]
