# Generated by Django 6.0.3 on 2026-05-05 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_simulationrun_cancelled_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='windinput',
            name='h5_datasets',
            field=models.TextField(blank=True, default='', help_text='Comma-separated list of dataset paths found in the HDF5 file.'),
        ),
        migrations.AddField(
            model_name='windinput',
            name='ts_end',
            field=models.FloatField(blank=True, help_text='Last time value in the per-hour time axis [s].', null=True),
        ),
        migrations.AddField(
            model_name='windinput',
            name='ts_n_hours',
            field=models.IntegerField(blank=True, help_text='Number of hours (columns) in the wind dataset.', null=True),
        ),
        migrations.AddField(
            model_name='windinput',
            name='ts_resolution',
            field=models.FloatField(blank=True, help_text='Time step size [s].', null=True),
        ),
        migrations.AddField(
            model_name='windinput',
            name='ts_start',
            field=models.FloatField(blank=True, help_text='First time value in the per-hour time axis [s].', null=True),
        ),
    ]
