# Generated by Django 6.0.3 on 2026-05-05 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_windinput_h5_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulationrun',
            name='output_path',
            field=models.CharField(blank=True, default='', help_text='Relative path (under MEDIA_ROOT/outputs/) to the saved HDF5 results file.', max_length=512),
        ),
    ]
