# Generated by Django 6.0.3 on 2026-05-05 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_simulationrun_output_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulationrun',
            name='description',
            field=models.CharField(blank=True, default='', help_text='Optional user note for this run (up to 200 chars).', max_length=200),
        ),
    ]
