# Generated by Django 6.0.3 on 2026-05-05 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_simulationrun_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulation',
            name='duration_days',
            field=models.PositiveIntegerField(blank=True, help_text='Override simulation duration (days). Truncates wind data to this many days. Leave blank to use the full wind file.', null=True),
        ),
    ]
