# Generated by Django 6.0.3 on 2026-05-11 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0021_simulation_datum_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulation',
            name='controller_file',
            field=models.CharField(blank=True, default='', help_text='Filename of a custom engineering controller in <data_root>/controllers/. Leave blank to use the built-in default controller.', max_length=255),
        ),
    ]
