# Generated by Django 6.0.3 on 2026-05-11 10:34

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0022_simulation_controller_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Controller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Controller', help_text='Display name for this controller.', max_length=100)),
                ('filename', models.CharField(help_text='Filename of the .py file in <data_root>/controllers/.', max_length=255, unique=True)),
                ('description', models.TextField(blank=True, default='', help_text='Optional description of what this controller does.')),
                ('author', models.CharField(blank=True, default='', help_text='Name of the person who created this controller.', max_length=150)),
                ('date_created', models.DateField(default=datetime.date.today, help_text='Date this controller was first created.')),
                ('verified', models.BooleanField(default=False, help_text='Mark True once the controller has been reviewed and validated.')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='simulation',
            name='controller_file',
            field=models.CharField(blank=True, default='', help_text='[Legacy] Filename of a custom controller. Superseded by controller FK.', max_length=255),
        ),
        migrations.AddField(
            model_name='simulation',
            name='controller',
            field=models.ForeignKey(blank=True, help_text='Custom engineering controller to use for this simulation. Leave blank to use the built-in default.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='simulations', to='dashboard.controller'),
        ),
    ]
