# Generated by Django 6.0.3 on 2026-05-11 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0023_controller_model_and_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='controller',
            name='edit_history',
            field=models.JSONField(blank=True, default=list, help_text='List of {"datetime": "ISO-8601", "author": "..."} entries, most recent last.'),
        ),
    ]
