# Generated by Django 5.2.14 on 2026-06-01 11:30

import dashboard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0026_rename_rkt_uc_battery_ktemp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='battery',
            old_name='rKt_lc',
            new_name='fKt',
        ),
        migrations.AlterField(
            model_name='battery',
            name='KTemp',
            field=models.FloatField(default=0.0693, help_text='Temperature degradation factor (°C)'),
        ),
        migrations.AlterField(
            model_name='battery',
            name='aiReplacementHour',
            field=models.JSONField(blank=True, default=None, help_text='Vector of the hours at which the battery was replaced (H)', null=True),
        ),
        migrations.AlterField(
            model_name='battery',
            name='arBatteryPower',
            field=models.JSONField(blank=True, default=None, help_text='Battery power flow in and out (W)', null=True),
        ),
        migrations.AlterField(
            model_name='battery',
            name='arDoD',
            field=models.JSONField(blank=True, default=None, help_text='Depth of Discharge of Battery', null=True),
        ),
        migrations.AlterField(
            model_name='battery',
            name='arInitialSoC',
            field=models.FloatField(default=0.5, help_text='Initial SoC'),
        ),
        migrations.AlterField(
            model_name='battery',
            name='arSoC',
            field=models.JSONField(blank=True, default=None, help_text='State of Charge of Battery', null=True),
        ),
        migrations.AlterField(
            model_name='battery',
            name='iNumReplacements',
            field=models.PositiveIntegerField(default=0, help_text='Number of times the battery has been replaced'),
        ),
        migrations.AlterField(
            model_name='battery',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='battery',
            name='rAlphaSei',
            field=models.FloatField(default=0.0575, help_text='Portion of the normalised energy capacity related to the solid electrolyte interphase (SEI) film'),
        ),
        migrations.AlterField(
            model_name='battery',
            name='rBatteryMWh',
            field=models.FloatField(default=15, help_text='Size of the battery (MWh)'),
        ),
        migrations.AlterField(
            model_name='battery',
            name='rBatteryProportionalGain',
            field=models.FloatField(default=0.0, help_text='Proportional gain of controller in bringing charge back to target'),
        ),
        migrations.AlterField(
            model_name='battery',
            name='rBatteryRating',
            field=models.FloatField(default=0.0, help_text='Rating (MW)'),
        ),
        migrations.AlterField(
            model_name='battery',
            name='rBetaSei',
            field=models.FloatField(default=121.0, help_text='Part of the exponential component of normalised energy capture due to SEI film'),
        ),
        migrations.AlterField(
            model_name='battery',
            name='rControlMinSoC',
            field=models.FloatField(default=0.5, help_text='The target state of charge of the battery for the controller'),
        ),
        migrations.AlterField(
            model_name='battery',
            name='rDodAv',
            field=models.FloatField(default=0.0, help_text='Average Depth of Discharge'),
        ),
        migrations.AlterField(
            model_name='battery',
            name='rFc',
            field=models.FloatField(default=0.0, help_text='Fatigue on battery due to cycles'),
        ),
        migrations.AlterField(
            model_name='battery',
            name='rFt',
            field=models.FloatField(default=0.0, help_text='Fatigue on battery due to temperature'),
        ),
        migrations.AlterField(
            model_name='battery',
            name='rInitialBatteryRating',
            field=models.FloatField(default=0.0, help_text='Initial size of the Battery (MW)'),
        ),
        migrations.AlterField(
            model_name='battery',
            name='rKd1',
            field=models.FloatField(default=140000.0, help_text='Depth of discharge degradation factor 1'),
        ),
        migrations.AlterField(
            model_name='battery',
            name='rKd2',
            field=models.FloatField(default=-0.501, help_text='Depth of discharge degradation factor 2'),
        ),
        migrations.AlterField(
            model_name='battery',
            name='rKd3',
            field=models.FloatField(default=-123000.0, help_text='Depth of discharge degradation factor 3'),
        ),
        migrations.AlterField(
            model_name='battery',
            name='rKs',
            field=models.FloatField(default=1.04, help_text='State of charge degradation factor'),
        ),
        migrations.AlterField(
            model_name='battery',
            name='rRCD',
            field=models.FloatField(default=1.0, help_text='Rated energy capacity (J)'),
        ),
        migrations.AlterField(
            model_name='battery',
            name='rSoCRef',
            field=models.FloatField(default=0.5, help_text='SoC Ref'),
        ),
        migrations.AlterField(
            model_name='battery',
            name='rSocAv',
            field=models.FloatField(default=0.0, help_text='Average State of Charge'),
        ),
        migrations.AlterField(
            model_name='battery',
            name='rSocMax',
            field=models.FloatField(default=0.0, help_text='Max State of Charge'),
        ),
        migrations.AlterField(
            model_name='battery',
            name='rSocMin',
            field=models.FloatField(default=0.0, help_text='Min State of Charge'),
        ),
        migrations.AlterField(
            model_name='battery',
            name='rTcRef',
            field=models.FloatField(default=55.0, help_text='Tc Ref (°C)'),
        ),
        migrations.AlterField(
            model_name='controller',
            name='file',
            field=models.FileField(db_column='filename', help_text='The .py controller file stored in <data_root>/controllers/. Upload here or create/edit via the simulation editor.', storage=dashboard.models._controller_storage, unique=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='controller',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='electrocellpem',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='electrolyserunit',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='simulationrun',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='thermalproperties',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='timeoutput',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='windinput',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
