# Generated by Django 5.2.14 on 2026-06-01 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0027_rename_rkt_lc_battery_fkt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battery',
            name='fKt',
            field=models.FloatField(default=4.14e-10, help_text='Elapsed time degradation factor (1/s)'),
        ),
    ]
