# Generated by Django 5.2.14 on 2026-06-02 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0029_rename_rcontrolminsoc_battery_rcontroltargetsoc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battery',
            name='rBatteryRating',
            field=models.FloatField(default=0.0, help_text='Rated energy capacity (J)'),
        ),
        migrations.AlterField(
            model_name='battery',
            name='rControlTargetSoC',
            field=models.FloatField(default=0.5, help_text='Target state of charge for the battery controller. The proportional controller drives SoC toward this value (can be above or below the current SoC).'),
        ),
        migrations.AlterField(
            model_name='battery',
            name='rInitialBatteryRating',
            field=models.FloatField(default=0.0, help_text='Initial rated energy capacity of the battery (J)'),
        ),
    ]
