# Generated by Django 5.2.14 on 2026-06-08 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0030_alter_battery_rbatteryrating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='battery',
            name='rReplacementThreshold',
            field=models.FloatField(default=0.7, help_text='Replacement threshold fraction of initial battery capacity (0-1)'),
        ),
    ]
