# Generated by Django 5.2.14 on 2026-06-12 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0031_add_battery_replacement_threshold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battery',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='controller',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='electrocellpem',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='electrolyserunit',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='simulationrun',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='thermalproperties',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='timeoutput',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='windinput',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='SimulationWindInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField(default=0, help_text='Order/sequence of this wind input within the simulation.')),
                ('year', models.PositiveIntegerField(default=1, help_text='Simulation year this wind input applies to.')),
                ('simulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wind_input_entries', to='dashboard.simulation')),
                ('wind_input', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simulation_entries', to='dashboard.windinput')),
            ],
            options={
                'ordering': ['year', 'sequence'],
                'unique_together': {('simulation', 'wind_input', 'year')},
            },
        ),
        migrations.RemoveField(
            model_name='simulation',
            name='wind_inputs',
        ),
        migrations.AddField(
            model_name='simulation',
            name='wind_inputs',
            field=models.ManyToManyField(blank=True, through='dashboard.SimulationWindInput', to='dashboard.windinput'),
        ),
    ]
