# Generated by Django 5.2.14 on 2026-06-12 10:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0033_simulationwindinput_year_validators'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulationwindinput',
            name='year',
            field=models.PositiveIntegerField(default=2026, help_text='Simulation year this wind input applies to (1900–2300).', validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2300)]),
        ),
    ]
