# Generated by Django 5.2.14 on 2026-06-12 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0034_alter_simulationwindinput_year'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='simulationwindinput',
            options={'ordering': ['sequence']},
        ),
        migrations.RemoveField(
            model_name='simulation',
            name='datum_date',
        ),
        migrations.AlterUniqueTogether(
            name='simulationwindinput',
            unique_together={('simulation', 'wind_input')},
        ),
        migrations.AddField(
            model_name='simulation',
            name='c',
            field=models.DateField(blank=True, help_text='Start date (00:00) used as the datetime axis origin for results charts. Defaults to today if not set.', null=True),
        ),
        migrations.RemoveField(
            model_name='simulationwindinput',
            name='year',
        ),
    ]
