# Generated by Django 5.2.14 on 2026-06-12 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0035_alter_simulationwindinput_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='simulation',
            old_name='c',
            new_name='datum_date',
        ),
    ]
