# Generated by Django 5.2.14 on 2026-06-12 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0036_restore_datum_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='simulation',
            name='iNumYears',
        ),
    ]
