# Generated by Django 5.2.14 on 2026-06-14 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0037_remove_inumyears'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulation',
            name='git_hash',
            field=models.CharField(blank=True, default='', help_text='Git commit hash of the code used to run this simulation.', max_length=40),
        ),
        migrations.AddField(
            model_name='simulation',
            name='version',
            field=models.CharField(blank=True, default='', help_text='Version of the code used to run this simulation.', max_length=20),
        ),
    ]
