# Generated by Django 5.2.14 on 2026-06-14 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0038_simulation_git_hash_simulation_version'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='simulation',
            name='git_hash',
        ),
        migrations.RemoveField(
            model_name='simulation',
            name='version',
        ),
        migrations.AddField(
            model_name='simulationrun',
            name='app_version',
            field=models.CharField(blank=True, default='', help_text='Version of r2h2 that produced this run.', max_length=20),
        ),
        migrations.AddField(
            model_name='simulationrun',
            name='git_hash',
            field=models.CharField(blank=True, default='', help_text='Git commit hash of the code that produced this run.', max_length=40),
        ),
    ]
