# Generated by Django 5.2.14 on 2026-06-14 20:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0039_simulationrun_app_version_git_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulation',
            name='datum_date',
            field=models.DateField(default=datetime.datetime(2026, 6, 14, 20, 49, 13, 81593), help_text='Start date (00:00) used as the datetime axis origin for results charts. Defaults to today if not set.', null=True),
        ),
    ]
