# Generated by Django 5.2.14 on 2026-06-14 20:58

import dashboard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0040_alter_simulation_datum_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulation',
            name='datum_date',
            field=models.DateField(default=dashboard.models.default_start_date, help_text='Start date (00:00) used as the datetime axis origin for results charts. Defaults to 1st Jan of the current year.'),
        ),
    ]
