# Generated by Django 5.2.14 on 2026-06-14 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0041_alter_simulation_datum_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulation',
            name='end_date',
            field=models.DateField(blank=True, help_text='End date for the simulation when using a specific date range.', null=True),
        ),
    ]
