# Generated by Django 5.2.14 on 2026-06-14 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0042_simulation_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulation',
            name='start_date',
            field=models.DateField(blank=True, help_text='Start date for the simulation when using a specific date range.', null=True),
        ),
    ]
