# Generated by Django 5.2.14 on 2026-06-15 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0043_simulation_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulationrun',
            name='run_end_date',
            field=models.DateField(blank=True, help_text='Effective end date used for this run (derived from simulation date range).', null=True),
        ),
        migrations.AddField(
            model_name='simulationrun',
            name='run_start_date',
            field=models.DateField(blank=True, help_text='Effective start date used for this run (derived from simulation date range).', null=True),
        ),
    ]
