# Generated by Django 5.2.14 on 2026-06-18 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0044_simulationrun_date_range'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electrocellpem',
            name='rA_cell',
            field=models.FloatField(default=1000.0, help_text='Area of the cell'),
        ),
        migrations.AlterField(
            model_name='electrocellpem',
            name='rD_rt',
            field=models.FloatField(default=-0.0045, help_text='Rate of change of resistance area with temperature'),
        ),
        migrations.AlterField(
            model_name='electrocellpem',
            name='rE_min0',
            field=models.FloatField(default=1.55, help_text='Reference cell voltage'),
        ),
        migrations.AlterField(
            model_name='electrocellpem',
            name='rF',
            field=models.FloatField(default=96485.0, help_text='Faraday Const F (C/mol)'),
        ),
        migrations.AlterField(
            model_name='electrocellpem',
            name='rI_rated',
            field=models.FloatField(default=3.0, help_text='The rated current density of the cell'),
        ),
        migrations.AlterField(
            model_name='electrocellpem',
            name='rR',
            field=models.FloatField(default=8.314, help_text='Gas Const R (J/mol·K)'),
        ),
        migrations.AlterField(
            model_name='electrocellpem',
            name='rR_0',
            field=models.FloatField(default=0.178, help_text='Reference resistance area'),
        ),
        migrations.AlterField(
            model_name='electrocellpem',
            name='rT_0',
            field=models.FloatField(default=20.0, help_text='The reference temperature for the electrolyser (i.e. the temperature used in design stage)'),
        ),
        migrations.AlterField(
            model_name='electrocellpem',
            name='rV_bank',
            field=models.FloatField(default=633.5, help_text='Parameter for the Faraday efficiency calculation'),
        ),
        migrations.AlterField(
            model_name='electrocellpem',
            name='rV_cellNom',
            field=models.FloatField(default=2.1, help_text='Parameter for the Faraday efficiency calculation'),
        ),
        migrations.AlterField(
            model_name='electrolyserunit',
            name='iN_banks',
            field=models.PositiveIntegerField(default=2, help_text='Number of banks in an electrolyser'),
        ),
        migrations.AlterField(
            model_name='electrolyserunit',
            name='iN_stacks',
            field=models.PositiveIntegerField(default=4, help_text='Number of Stacks in a bank'),
        ),
        migrations.AlterField(
            model_name='electrolyserunit',
            name='iNumElectro',
            field=models.PositiveIntegerField(default=5, help_text='Number of Electrolysers in the system'),
        ),
        migrations.AlterField(
            model_name='electrolyserunit',
            name='rRampUp_W_s',
            field=models.FloatField(blank=True, default=205000.0, help_text='Positive ramp rate limit for the electrolyser (W/s)', null=True),
        ),
        migrations.AlterField(
            model_name='electrolyserunit',
            name='rTimeConst',
            field=models.FloatField(default=0, help_text='Time constant for the controller to smooth the power flow to the electrolyser (s)'),
        ),
        migrations.AlterField(
            model_name='electrolyserunit',
            name='rTurnDownRatio',
            field=models.FloatField(default=0.125, help_text='The turn down ratio of the electrolyser - the fraction of power that is the minimum operational power'),
        ),
        migrations.AlterField(
            model_name='electrolyserunit',
            name='r_f',
            field=models.FloatField(default=3.33e-07, help_text='The fatigue cycle degradation factor'),
        ),
        migrations.AlterField(
            model_name='electrolyserunit',
            name='r_o',
            field=models.FloatField(default=0.000147, help_text='The on-off degradation factor (V)'),
        ),
        migrations.AlterField(
            model_name='electrolyserunit',
            name='r_s',
            field=models.FloatField(default=1.42e-10, help_text='The steady state degradation factor (1/s)'),
        ),
    ]
