# Generated by Django 5.2.14 on 2026-06-18 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0045_alter_electrocellpem_ra_cell_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="simulation",
            name="collect_1hz_data",
            field=models.BooleanField(
                default=False,
                help_text="Enable collection of per-second (1Hz) data over a limited time period.",
            ),
        ),
        migrations.AddField(
            model_name="simulation",
            name="collect_1hz_end_date",
            field=models.DateField(
                blank=True,
                help_text="End date for 1Hz data collection (inclusive). Must be after start_date and within 3 months.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="simulation",
            name="collect_1hz_start_date",
            field=models.DateField(
                blank=True,
                help_text="Start date for 1Hz data collection (inclusive). Must be before end_date and within 3 months.",
                null=True,
            ),
        ),
    ]
