# Generated by Django 5.2.14 on 2026-06-18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0046_simulation_collect_1hz_data_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="simulation",
            name="collect_1hz_data",
            field=models.BooleanField(
                default=True,
                help_text="Enable collection of per-second (1Hz) data over a limited time period.",
            ),
        ),
    ]
