# Generated by Django 5.2.14 on 2026-06-18 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0047_alter_simulation_collect_1hz_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="electrocellpem",
            name="rR_0",
            field=models.FloatField(
                default=0.345, help_text="Reference resistance area"
            ),
        ),
    ]
