# Generated by Django 5.2.14 on 2026-06-19 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0048_alter_electrocellpem_rr_0'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battery',
            name='KTemp',
            field=models.FloatField(default=0.0693, help_text='Temperature degradation factor'),
        ),
        migrations.AlterField(
            model_name='battery',
            name='fKt',
            field=models.FloatField(default=4.14e-10, help_text='Elapsed time degradation factor'),
        ),
        migrations.AlterField(
            model_name='battery',
            name='rBatteryMWh',
            field=models.FloatField(default=15, help_text='Size of the battery'),
        ),
        migrations.AlterField(
            model_name='electrocellpem',
            name='iNumCurrent',
            field=models.PositiveIntegerField(default=1000, help_text='Number of elements in the range of the current'),
        ),
        migrations.AlterField(
            model_name='electrocellpem',
            name='rF1',
            field=models.FloatField(default=0.25, help_text='Parameter for the Faraday efficiency calculation'),
        ),
        migrations.AlterField(
            model_name='electrocellpem',
            name='rF2',
            field=models.FloatField(default=0.996, help_text='Parameter for the Faraday efficiency calculation'),
        ),
        migrations.AlterField(
            model_name='electrocellpem',
            name='rI_bank',
            field=models.FloatField(default=3000.0, help_text='Current for the bank (A/cm^2)'),
        ),
        migrations.AlterField(
            model_name='electrocellpem',
            name='rR',
            field=models.FloatField(default=8.314, help_text='Ideal gas constant R (J/mol·K)'),
        ),
        migrations.AlterField(
            model_name='electrocellpem',
            name='rT',
            field=models.FloatField(default=55.0, help_text='Initial operating temperature of the cell (°C)'),
        ),
        migrations.AlterField(
            model_name='electrocellpem',
            name='rV_bank',
            field=models.FloatField(default=633.5, help_text='Voltage of the bank (V)'),
        ),
        migrations.AlterField(
            model_name='electrocellpem',
            name='rV_cellNom',
            field=models.FloatField(default=2.1, help_text='Cell voltage at nominal temperature and current (V)'),
        ),
        migrations.AlterField(
            model_name='electrolyserunit',
            name='arDegradationTotal',
            field=models.JSONField(blank=True, default=None, help_text='The total degradation each time step (used in calcs)', null=True),
        ),
        migrations.AlterField(
            model_name='electrolyserunit',
            name='iN_stacks',
            field=models.PositiveIntegerField(default=4, help_text='Number of stacks in a bank'),
        ),
        migrations.AlterField(
            model_name='electrolyserunit',
            name='iNumElectro',
            field=models.PositiveIntegerField(default=5, help_text='Number of electrolysers in the system'),
        ),
        migrations.AlterField(
            model_name='electrolyserunit',
            name='iNumUnits',
            field=models.PositiveIntegerField(blank=True, default=None, help_text='The number of units in the system (worked out by the code)', null=True),
        ),
        migrations.AlterField(
            model_name='electrolyserunit',
            name='rAncilliaryPowerFrac',
            field=models.FloatField(default=0.0, help_text='The fraction of the rated power that must always be provided for the system (for ancillary services and BOP)'),
        ),
        migrations.AlterField(
            model_name='electrolyserunit',
            name='rDeadBandRatio',
            field=models.FloatField(default=2.0, help_text='Used by the controller'),
        ),
        migrations.AlterField(
            model_name='electrolyserunit',
            name='rDegradation',
            field=models.FloatField(default=1e-30, help_text='The change in degradation each time step (V)'),
        ),
        migrations.AlterField(
            model_name='electrolyserunit',
            name='rRampDown_W_s',
            field=models.FloatField(blank=True, default=505000.0, help_text='Negative ramp rate limit for the electrolyser', null=True),
        ),
        migrations.AlterField(
            model_name='electrolyserunit',
            name='rRampUp_W_s',
            field=models.FloatField(blank=True, default=205000.0, help_text='Positive ramp rate limit for the electrolyser', null=True),
        ),
        migrations.AlterField(
            model_name='electrolyserunit',
            name='rSummedDegradation',
            field=models.FloatField(default=1e-30, help_text='The sum of the degradation on the unit. The initial value can be used to set a starting value for degradation'),
        ),
        migrations.AlterField(
            model_name='electrolyserunit',
            name='rTimeConst',
            field=models.FloatField(default=0, help_text='Time constant for the controller to smooth the power flow to the electrolyser'),
        ),
        migrations.AlterField(
            model_name='electrolyserunit',
            name='r_o',
            field=models.FloatField(default=0.000147, help_text='The on-off degradation factor'),
        ),
        migrations.AlterField(
            model_name='electrolyserunit',
            name='r_s',
            field=models.FloatField(default=1.42e-10, help_text='The steady state degradation factor'),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='collect_1hz_end_date',
            field=models.DateField(blank=True, help_text='End date for 1Hz data collection (inclusive). Must be after or equal to start_date. Long ranges create very large output files.', null=True),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='collect_1hz_start_date',
            field=models.DateField(blank=True, help_text='Start date for 1Hz data collection (inclusive). Must be before or equal to end_date. Long ranges create very large output files.', null=True),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='rDivisor',
            field=models.FloatField(blank=True, default=None, help_text='Divisor for normalizing wind power input (e.g. max power of single turbine)', null=True),
        ),
        migrations.AlterField(
            model_name='thermalproperties',
            name='rAmbientTemp',
            field=models.FloatField(default=15.0, help_text='Ambient temperature near electrolyser'),
        ),
        migrations.AlterField(
            model_name='thermalproperties',
            name='rTauCooling',
            field=models.FloatField(default=1800.0, help_text='Time constant for cooling'),
        ),
        migrations.AlterField(
            model_name='thermalproperties',
            name='rTauHeating',
            field=models.FloatField(default=1200.0, help_text='Time constant for heating'),
        ),
    ]
