# Generated by Django 5.2.14 on 2026-06-19 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0049_alter_battery_ktemp_alter_battery_fkt_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='battery',
            old_name='fKt',
            new_name='rKt',
        ),
        migrations.RenameField(
            model_name='electrolyserunit',
            old_name='rAncilliaryPowerFrac',
            new_name='rAncillaryPowerFrac',
        ),
        migrations.RenameField(
            model_name='electrolyserunit',
            old_name='rAncilliaryPower_s',
            new_name='rAncillaryPower_s',
        ),
    ]
