# Generated by Django 5.2.14 on 2026-06-22 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0053_alter_electrolyserunit_rrampup_ws_default_and_backfill'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulation',
            name='hz_variables',
            field=models.JSONField(blank=True, default=list, help_text='List of t_out attribute names to capture at 1Hz. Empty list means capture all default channels. Only arrays of length T (time) are valid.'),
        ),
    ]
